package io.softwareintelligence.model;

public enum EntityKind {
    REPOSITORY, FILE, PACKAGE, TYPE, INTERFACE, METHOD, FIELD,
    CONTROLLER, SERVICE, REPOSITORY_COMPONENT, ENTITY, CONFIGURATION,
    ENDPOINT, TOPIC, DATABASE_TABLE, TRANSACTION, WORKFLOW, BUSINESS_CAPABILITY,
    SECURITY_GUARD, EXTERNAL_SERVICE, CONFIGURATION_PROPERTY, MODULE,
    EXTERNAL_SYMBOL
}
