package io.softwareintelligence.model;

public enum RelationKind {
    CONTAINS, DECLARES, IMPORTS, EXTENDS, IMPLEMENTS, OVERRIDES, CALLS, READS, WRITES, CREATES, THROWS, CATCHES,
    EXPOSES, PERSISTS, PUBLISHES, CONSUMES, CONFIGURES, PARTICIPATES_IN, DEPENDS_ON
}
